### ISSUE TITLE
ability to manage "Configure System"

### ISSUE THREAD

**Issue by neoice** [jenkinsci/puppet-jenkins#194]
we're moving a bunch of legacy build processes over to Jenkins. these builds depend on Maven and specific JDK `PATH`s. Jenkins provides some awesome tools under "Configure System": like "Maven" and "JDK". it would be nice to codify these in Puppet code so we could run the same build in multiple environments, re-deploy Jenkins instances trivially, support isolated testing&&development *of* the build process itself, etc.

**Comment by jhoblitt** [comment]
Since jenkins flushes it's configuration on restart, the above strategy is likely to be unreliable.

This is a frequently requested feature but it's essentially impossible to implement generic support for all possible configurations so I'm going to close this issue.  Feature requests for specific settings would be much more tractable.
