### ISSUE TITLE
Plugins are installed each time and restarting service

### ISSUE THREAD

**Issue by iax7** [jenkinsci/puppet-jenkins#219]
Every time puppet runs, the plugin installation is run even when it already exists, causing a service restart each time...

**Comment by iax7** [comment]
I have researched this a little further, the problem is that the facter ::jenkins_plugins is returning an empty string. In a quick view I didn't find the root issue in that facter.

**Comment by richjm** [comment]
This happens if the plugin directory is anything other than "~jenkins/plugins" as this is where lib/puppet/jenkins.rb expects it to be. A quick worked around is symlinking "~jenkins/plugins" to the actual location.

**Comment by tstibbs** [comment]
There is a request [here](https://github.com/jenkinsci/puppet-jenkins/issues/365) that captures the root cause of this (that this module always assumes jenkins is intalled in ~jenkins).

**Comment by cjmachado** [comment]
Hi there!
I'm commenting on a closed issue because I believe it's still not fixed. My environment is (fresh install):

OS: CentOS 6.8 x86_64
Ruby: 1.8.7 (2013-06-27 patchlevel 374)
Puppet: 3.8.7
puppet-jenkins: 1.7.0
Jenkins: 1.651.3-1.1 
Java: Oracle's 1.7.0_80

When I run puppet for the first time, Jenkins is installed but only the credentials.hpi file (and corresponding .pinned file) is placed in the plugins directory. Plugin file is not uncompressed and due to this, "puppet-jenkins" will always try to install the plugins on each run, because it searches for directories inside the plugins directory (there is none, because the HPI file is not expanded). The code that searches for plugin directories is at lib/facter/jenkins.rb (method "available").
To workaround this issue, I changed the archive resource in plugin.pp to include the following attributes:

extract         => true,
extract_path    => $jenkins::plugin_dir,
extract_command => "unzip %s -d ${::jenkins::plugin_dir}/${title}",
creates         => "${::jenkins::plugin_dir}/${title}",
user            => $::jenkins::user,
group           => $::jenkins::group,

After running puppet with these changes applied, the plugins directory include several other plugins other than "credentials" and Jenkins no longer restarts.
