### ISSUE TITLE
need new defined type for managing $JENKINS_HOME/config.xml

### ISSUE THREAD

**Issue by hesco** [jenkinsci/puppet-jenkins#313]
A (recursive) review of jenkins/( manifests | lib )/* and README.md reveals nothing suitable for managing the base configuration for a jenkins installation under puppet management.  Perhaps I have missed something obvious, in which case I would certainly appreciate a pointer or guidance.  Otherwise, this strikes me as a big missing.  I would prefer to be able to dynamically manage these settings from a puppet manifest, rather than to have to create some sort of golden image or template deployed from a File[] resource.   Ideally I'd love to feed a node specific complex data structure from hiera to an ensure_resources function call and have it do the right thing.   Has anyone done work in this arena?  Anyone with a similar itch to scratch who would care to pair up to deliver this new functionality?

**Comment by hesco** [comment]
From what I reported here:  
https://groups.google.com/forum/#!topic/jenkinsci-users/LccsaGqIo6k  

it seems apparent that the API does not support this and that augeaus, or concat fragments, or a File[] resource or direct ruby xml xpath manipulations will be required to expose this functionality.  Last night I began setting up a test environment to ensure that the regression suite starts out as green before I start hacking to see where I might take this.  When I left the office I was still chasing the Gemfile dependencies, a task I hope to complete this morning.  

Again I ask:

Has anyone done work in this arena? Anyone with a similar itch to scratch who would care to pair up to deliver this new functionality?

Even if you do not have time to contribute code or tests to this effort, if you have any insight on architecture or comments on the problem space, your feedback at this time as I begin this project would be appreciated.  

Thanks,
-- Hugh

**Comment by hesco** [comment]
Related post to the jenkins-dev@ list:

Should API support management of $JENKINS_HOME/config.xml ???
https://groups.google.com/forum/?hl=en#!topic/jenkinsci-dev/a-gKzV6Z2Q8

**Comment by hesco** [comment]
Also, let me ask the core maintainers of this project:

Were we to invest in this new defined type, would there be interest in merging it back into the puppet-jenkins module, or would be left to maintain an in-house fork?  

-- Hugh

**Comment by jhoblitt** [comment]
@hesco Jenkins dynamically updates the primary `config.xml` based on configuration via it's API.  That's primarily via through the HTML UI but also via RESTish interfaces, uploaded administrative groovy scripts that may interact with the internal API, and/or cli jar commands.  This module already manages a number of settings in `config.xml` via built in cli jar commands and via a groovy "helper script" that is passed in.  Directly managing that file is difficult for a number of reasons.

* The format is both complex and is changed by the presence of plugins.
* Its functionally a set of literal API calls rather than a defined configuration format.  I don't believe there is a promise of the format being 100% identical between jenkins revisions and I have seen whitespace changes between versions -- whitespace alone would cause problems with idempotent.  * Jenkins flushes its internal state out when restarted so the only opportunity to modify that file is when jenkins is not running.
* Not all "global" configuration is expressed in that file.

It certain would be possible to generate `config.xml` external to jenkins and copy it into place but at the cost of being able to configure very little via the WWW UI without violating idempotence. Jenkins already has an API for generating that file so that is what the puppet, chef, and ansible modules all use.  The situation is certainly not convenient for configuration management but it's inherent to jenkins design.

I am not a maintainer of this module but my suggestion would be to open issues for state that you want to manage that is not currently exposed via this modules classes and types.

**Comment by waynr** [comment]
@hesco I have this exact same itch, I want Jenkins to have an API endpoint that openstack-infra/jenkins-job-builder can hit with generated XML to managed Jenkins global configuration. My freenode nick is the same as my github username if you want to discuss via PM.

**Comment by hesco** [comment]
@waynr: Great to hear.  This project is for my day job where I am locked out of IRC access by the corporate network security folks.  Can you please contact me at hesco at yourmessagedelivered dot com with a phone number or email address where I can contact you during office hours?  I work EST hours.  I rarely monitor that address from the office, so there would be some lag time in getting a response, but once we are in real time communication in a forum which is not publicly archived, I can provide you contact information for reaching me during office hours.  

@jhoblitt: can you provide any pointers please to whatever documentation might already exist on the Jenkins API for configuration management?  When a plugin wants to store configuration in config.xml, what is the process for doing so?  I have never hacked on the Jenkins code base and am seeking guidance on where and how to begin this process.  

-- Hugh

**Comment by hesco** [comment]
btw: I have changed the subject of this ticket to reflect that an appropriate architecture here might involve writing a native type with ruby in lib/puppet/, rather than a defined type with puppet DSL in manifests/.

**Comment by jhoblitt** [comment]
@hesco There is no formal API for managing `config.xml`.  It is generated by the Xstream library to serialize jenkins' internal state to XML.

#382 adds a number of native types/provides, many of which effect `config.xml` by interactive with jenkin's internal API via groovy fragments.  The framework is there to build out additional functionality.  Take a look at https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md

@waynr You may want to take a look at the new `jenkins_job` type.  One possible approach would be to create a "job-builder" provider that inherits the existing `cli` provider

I'm going to close out this issue as it's a bit to generic to be actionable.
