### ISSUE TITLE
Preparing a release for PuppetConf

### ISSUE THREAD

**Issue by rtyler** [jenkinsci/puppet-jenkins#384]
Since @jhoblitt and I will both be at PuppetConf, here's a reminder that we should finally cut the release of 1.6.0 to puppet forge

**Comment by jhoblitt** [comment]
:+1:

**Comment by jhoblitt** [comment]
@rtyler I'm fairly confident that the issue with the native types blowing up under puppetserver reported in #385 is only triggered if one of the new types is added to the manifest -- users merely upgrading should not be effected.  I've resorted to the "document it" approach (with a workaround) https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md#puppetserver instead of continuing to hold the release.

**Comment by jhoblitt** [comment]
Lets SHIP IT!

**Comment by rtyler** [comment]
@jhoblitt alright, i'll package things up tonight before I pass out :)

**Comment by jhoblitt** [comment]
:dancer:

**Comment by rtyler** [comment]
SHAZAM
